version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=pipas_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
